name: uni_ocr
description: A universal ocr client.
version: 0.1.0
homepage: https://github.com/biyidev/uni_ocr

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ocr_engine_builtin: ^0.1.0
  ocr_engine_youdao: ^0.1.0
  uni_ocr_client: ^0.1.0

dev_dependencies:
  test: ^1.0.0
